const luyagent = {
  slug: 'luyagent',
  name: 'LUYAGENT',
  category: 'Private sales automation',
  title: 'Turn Telegram conversations into confirmed orders - even when you are away.',
  intro: 'LUYAGENT helps Cambodian shops answer questions, show available products, build carts, collect delivery details and move each customer toward payment. Orders, inventory and customer records remain on the seller\'s own Windows system.',
  audience: 'Solo sellers, family shops and small Cambodian businesses already taking orders through Telegram.',
  problemTitle: 'Every unanswered chat can become a lost order.',
  problems: ['Customers wait for repeated product, stock and delivery answers.', 'Cart, address, payment evidence and order status become disconnected.', 'Sellers need automation without silently approving payments or difficult conversations.'],
  outcomes: [['Fewer missed orders', 'Customers can browse, ask questions and begin checkout without waiting for the seller.'], ['A controlled order flow', 'Product, stock, address, payment method and status stay connected from chat to confirmation.'], ['Seller control when it matters', 'Payments and difficult conversations are surfaced for human review.']],
  workflow: ['Telegram conversation', 'Catalog and FAQ', 'Cart and address', 'COD or bank QR', 'Payment evidence', 'Seller confirmation', 'Receipt and handoff'],
  visuals: {
    problem: 'images/products/luyagent/sales-problems-v2.png',
    outcomes: [
      'images/products/luyagent/fewer-missed-orders.png',
      'images/products/luyagent/controlled-order-flow.png',
      'images/products/luyagent/seller-control.png',
    ],
    workflow: 'images/products/luyagent/order-workflow-v2.png',
    showcase: 'images/products/luyagent/seller-operations.png',
    portfolio: 'images/products/luyagent/portfolio-order-journey.png',
  },
  capabilities: ['Khmer and English customer journeys', 'Catalog, search, cart and checkout', 'Stock-aware inventory controls', 'ABA, Wing and ACLEDA payment options', 'Payment screenshot review', 'Order confirmation and PDF receipts', 'Human handoff and assisted replies', 'Spreadsheet product import', 'Local seller dashboard and SQLite records'],
  proof: ['Telegram-ready', 'Seller-approved payments', 'Local operational data'],
  privacy: 'Catalog, orders and customer records are stored in the LUYAGENT installation. Assisted replies currently require configured model access.',
  dataView: 'luyagent',
  pilot: 'LUYAGENT Seller Pilot',
  pilotCopy: 'Bring your current Telegram catalog, payment methods and approval process. We configure one focused seller workflow and verify it with your team.',
  primaryCta: 'Request a LUYAGENT demo',
  secondaryCta: 'See the seller dashboard',
  faqs: [['Does LUYAGENT confirm payments automatically?', 'No. Payment evidence is surfaced for seller verification or rejection.'], ['Which selling channel is ready today?', 'Telegram is the completed sales channel. Additional channels should be confirmed during assessment.'], ['Where is business data stored?', 'The catalog, customer, order and payment records use the local LUYAGENT installation.']],
}

const khmeradv = {
  slug: 'khmeradv',
  name: 'KhmerADV',
  category: 'Agency media operations',
  title: 'Run every brand, campaign and channel from one controlled workspace.',
  intro: 'KhmerADV turns campaign briefs into approved, branded content across social channels. Manage brand rules, visual references, production stages and publishing from one operational command center.',
  audience: 'Agencies and marketing teams operating multiple brands, campaigns and approval flows.',
  problemTitle: 'Agency operations break when every campaign lives in a different tool.',
  problems: ['Brand rules, visual references and channel drafts are easy to mix.', 'Teams cannot see where a production run is blocked or awaiting approval.', 'Publishing status, retries and platform permissions are difficult to track.'],
  outcomes: [['Keep brands separated', 'Manage campaign rules, references and channel settings without mixing client assets.'], ['See the production pipeline', 'Track copy, image, branding, approval and delivery stages in one workspace.'], ['Approve before publishing', 'Review every branded post before it reaches an enabled public channel.']],
  workflow: ['Campaign brief', 'Copy and art direction', 'Image production', 'Brand composition', 'Human approval', 'Channel publishing', 'Delivery and correction'],
  visuals: {
    outcomes: [
      'images/products/khmeradv/brands-separated.png',
      'images/products/khmeradv/production-pipeline.png',
      'images/products/khmeradv/approval-gate.png',
    ],
    workflow: 'images/products/khmeradv/campaign-workflow.png',
    showcase: 'images/products/khmeradv/production-command-center.png',
    portfolio: 'images/products/khmeradv/portfolio-campaign-command.png',
  },
  capabilities: ['Multi-campaign workspaces', 'Brand rules and visual references', 'Sequential production queue', 'Copy and ComfyUI image pipeline', 'Remotion brand composition', 'Telegram and dashboard approval', 'Facebook, Instagram, TikTok, LinkedIn and Telegram publishers', 'Retry protection and event history', 'Supported post correction and removal'],
  proof: ['Multi-campaign', 'Human-approved', 'Brand-controlled', 'Channel-ready'],
  privacy: 'KhmerADV combines local media production with configured copy, CDN and social-platform services. Channel availability depends on account permissions and platform approval.',
  dataView: 'khmeradv',
  pilot: 'Agency Command Center Pilot',
  pilotCopy: 'Select one brand and one campaign. We configure its rules, references, approval path and confirmed channels, then run the workflow end to end.',
  primaryCta: 'Plan an agency pilot',
  secondaryCta: 'See the campaign workflow',
  faqs: [['Is KhmerADV only a social scheduler?', 'No. It connects campaign brief, production, branding, approval and publishing.'], ['Can it manage separate brands?', 'Yes. Campaign and brand records keep rules, references and channel settings separated.'], ['Does every channel work automatically?', 'Publishing depends on each platform account, permission and approval status.']],
}

const hermes = {
  slug: 'hermes-post',
  name: 'Hermes Post',
  category: 'Content assistant for small business',
  title: 'Keep your business visible without becoming a full-time content manager.',
  intro: 'Hermes Post helps shops, independent creators and small teams turn a simple idea into an approved post, matching visual and practical publishing schedule.',
  audience: 'Small shops, bloggers, creators and owner-led businesses that need consistent content without agency complexity.',
  problemTitle: 'Posting consistently should not take over your working week.',
  problems: ['Ideas remain unfinished because writing and image creation happen separately.', 'Small teams lose time rewriting the same message for each platform.', 'Drafts, approvals and scheduled posts are difficult to see at a glance.'],
  outcomes: [['Create from one idea', 'Turn an offer, product, announcement or story into platform-ready drafts.'], ['Keep your voice', 'Edit and approve every message before it becomes part of the schedule.'], ['Plan content in one sitting', 'Prepare a practical week or month of posts, then publish or export.']],
  workflow: ['Idea or offer', 'Channel choice', 'Draft and rewrite', 'Image creation', 'Human approval', 'Schedule or publish', 'Export and reuse'],
  visuals: {
    outcomes: [
      'images/products/hermes-post/one-idea.png',
      'images/products/hermes-post/voice-approval.png',
      'images/products/hermes-post/content-calendar.png',
    ],
    workflow: 'images/products/hermes-post/content-workflow.png',
    showcase: 'images/products/hermes-post/schedule-board.png',
    portfolio: 'images/products/hermes-post/portfolio-content-week.png',
  },
  capabilities: ['Topic and content-draft creation', 'Platform and content-type variants', 'Editing, rewrite, approval and rejection', 'ComfyUI or Gemini image workflows', 'Selectable image formats', 'Editorial calendar and posting queue', 'Dashboard and Telegram control', 'Markdown export', 'Human-approved correction memory', 'Facebook, Instagram, LinkedIn and Telegram publishing'],
  proof: ['Simple workflow', 'Human approval', 'Content calendar', 'Telegram control'],
  privacy: 'Hermes Post uses configured online providers for text and connected publishing. Manual export remains available when direct publishing is not appropriate.',
  dataView: 'hermes',
  pilot: 'First Content Week',
  pilotCopy: 'Bring one week of offers, announcements or stories. We configure your channels and produce an approved, practical posting queue.',
  primaryCta: 'Create your first content week',
  secondaryCta: 'See how Hermes Post works',
  faqs: [['Is Hermes Post an agency tool?', 'No. It is intentionally simpler than KhmerADV and designed for one small business or creator workflow.'], ['Can I approve from my phone?', 'Telegram can act as a simple remote for review and approval.'], ['Does it publish to TikTok?', 'No TikTok publisher is currently part of Hermes Post. Supported connected channels should be confirmed during setup.']],
}

const kramos = {
  slug: 'kramos',
  name: 'KramOS',
  category: 'Compliance and document control',
  title: 'Every compliance finding should show its evidence.',
  intro: 'KramOS reviews business documents against verified rules, links every issue to its source and keeps the final decision with your team. Built for Cambodian operations and designed to run under your control.',
  audience: 'Cambodian factories, exporters, finance teams, internal auditors and compliance managers.',
  problemTitle: 'A finding without a source is not a defensible decision.',
  problems: ['Operational evidence is scattered across scans, PDFs, Office files and languages.', 'Reviewers repeat the same checks without a consistent decision trail.', 'Generic document tools cannot explain the applicable source or preserve human accountability.'],
  outcomes: [['Review faster', 'Extract important fields and route documents to the relevant operational checks.'], ['Trace every issue', 'Keep the document, source page, applicable rule and reviewer action connected.'], ['Preserve responsibility', 'Correct, resolve, ignore or override with a complete human approval trail.']],
  workflow: ['Secure intake', 'OCR and classification', 'Department routing', 'Deterministic checks', 'Evidence-linked finding', 'Human decision', 'Audit trail and export'],
  visuals: {
    outcomes: [
      'images/products/kramos/review-faster.png',
      'images/products/kramos/evidence-lineage.png',
      'images/products/kramos/reviewer-action.png',
    ],
    workflow: 'images/products/kramos/review-workflow.png',
    showcase: 'images/products/kramos/evidence-control-board.png',
    portfolio: 'images/products/kramos/portfolio-evidence-decision.png',
  },
  capabilities: ['Files, batches and folder intake', 'Khmer, English and Chinese script detection', 'Local PDF, image and Office processing', 'Tax, audit, customs, logistics, garment, ISO and factory checks', 'Mandatory evidence for stored findings', 'Cross-document duplicate and sequence controls', 'Reviewer correction, resolution and override', 'Document, language, OCR and department analytics', 'Tenant isolation and audit trail'],
  proof: ['Evidence-linked', 'Deterministic checks', 'Human-approved', 'Controlled pilot'],
  privacy: 'KramOS is currently positioned as a controlled local pilot. It supports compliance review but does not replace legal or professional judgement and does not guarantee an audit result.',
  dataView: 'kramos',
  pilot: 'KramOS Controlled Pilot',
  pilotCopy: 'Choose one document family - such as supplier invoices, licences or customs declarations. We configure the verified review rules and measure the workflow before expanding.',
  primaryCta: 'Book a controlled pilot',
  secondaryCta: 'See the review workflow',
  disclaimer: 'KramOS supports evidence collection and controlled review. Qualified people remain responsible for compliance conclusions.',
  faqs: [['Is KramOS production SaaS?', 'Not yet. The current offer is a controlled local pilot with a human reviewer.'], ['Can it invent a compliance finding?', 'The findings path uses deterministic controls and requires supporting evidence.'], ['Can reviewers override a result?', 'Yes. Overrides require a recorded reason and remain part of the audit trail.']],
}

Object.assign(luyagent, {
  intro: 'LUYAGENT answers your customers on Telegram while you are busy. It shows your products, builds the cart, takes the delivery address and collects the payment proof. Then it stops and waits for you. You confirm the payment. You handle the hard conversations. Your products, orders and customer details stay on your own computer.',
  fit: {
    forYou: ['You already sell on Telegram and answer the same questions every day.', 'You lose orders because you cannot reply fast enough at night or on weekends.', 'You take payment by cash on delivery, ABA, Wing or ACLEDA.', 'You want software to handle repetition while you approve the money.', 'You have one Windows computer that can stay on.'],
    notForYou: ['You need payments confirmed without human review.', 'You sell mainly through Facebook, Instagram or a web shop.', 'You need many staff accounts with separate permissions.', 'You cannot leave a computer running and do not want local deployment.'],
  },
  useCases: [['The shop that closes at 6pm', 'Customers can browse, build a cart and send payment proof after closing. The seller reviews every payment the next morning.'], ['One product line, many repeated questions', 'LUYAGENT answers from the real catalogue and FAQ in Khmer or English, and passes unknown questions to the seller.'], ['One connected order record', 'Conversation, cart, address, payment proof and receipt remain attached to the same order.'], ['A real receipt after approval', 'Once the seller confirms payment, LUYAGENT produces a PDF receipt and hands the order back for delivery.']],
  boundaries: ['It never confirms a payment. It collects proof and shows it to the seller.', 'It never invents stock or guesses an unknown answer.', 'Complaints, refunds and disputes go directly to a person.', 'Catalogue, orders and customer records stay in the local installation.', 'Delivery remains the seller\'s responsibility.'],
  requirements: { runsOn: 'Your own Windows computer.', needs: ['A Telegram account for the shop.', 'A product list; a spreadsheet is enough.', 'Cash on delivery and/or ABA, Wing or ACLEDA payment details.', 'A computer that stays on while the shop should answer.'], optional: ['Assisted replies for questions outside the FAQ, using a model connection you configure.'] },
  dataHandling: 'Your catalogue, orders, customers and payment records are stored in the LUYAGENT installation on your machine. Telegram carries the messages. If assisted replies are enabled, only those questions use the model connection you configure. Urban Explorer Labs does not hold your business data on its own server.',
  pilotPlan: [['1', 'Set up your shop', 'Load products, prices and stock; connect Telegram and payment methods.'], ['2', 'Teach it your answers', 'Turn real repeated questions into the FAQ and define every handoff.'], ['3', 'Run live, watching', 'Use real orders while you confirm every payment and we correct failures.'], ['4', 'Review the evidence', 'Review what it handled, what it escalated and what it got wrong before deciding whether to continue.']],
  faqs: [...luyagent.faqs, ['Will it answer in Khmer?', 'Yes. Khmer and English customer journeys are supported.'], ['What if it does not know the answer?', 'It passes the question to you instead of guessing.'], ['Can I take over a conversation?', 'Yes. Human handover is built in.'], ['What happens if the internet drops?', 'Your installation and records remain local. Telegram delivery resumes with the connection.'], ['Do I need technical knowledge?', 'No. You need a product list and a Windows computer that stays on.'], ['Can I import a spreadsheet?', 'Yes. Spreadsheet product import is supported.'], ['What if I stop?', 'The data remains in your installation on your machine.']],
  roadmap: { label: 'Planned', note: 'Not available today. Confirm scope during assessment.', items: ['Selling channels beyond Telegram', 'Multiple staff accounts with separate permissions', 'Automated delivery-partner handoff'] },
})

Object.assign(khmeradv, {
  intro: 'KhmerADV runs multi-brand campaign production as one controlled pipeline. A brief becomes copy, art direction, generated imagery and brand composition, then stops at a human approval gate before any enabled channel receives it. Brand rules, references and channel credentials are scoped per campaign, so client assets cannot bleed across accounts.',
  capabilities: khmeradv.capabilities.filter((item) => !item.includes('TikTok')),
  fit: { forYou: ['You operate multiple brands and must prevent assets crossing between them.', 'Your production follows visible copy, art, image, brand, approval and publish stages.', 'Every live post needs approval from a named person.', 'Each channel has its own account, permission and approval state.', 'Corrections and removals must remain in the event history.'], notForYou: ['You only need a scheduler.', 'You want unattended publishing.', 'You run one brand on one simple calendar.', 'You expect every platform to work before account permission and platform review.'] },
  useCases: [['Four client brands, no cross-contamination', 'Campaign records hold their own rules, reference imagery and channel settings without a shared global asset pool.'], ['Find the blocked run', 'Every campaign exposes the stage where work is waiting or has failed.'], ['Approval that leaves a record', 'Approve, reject or return a composition; the named decision remains attached to the run.'], ['Correct a live post', 'Supported posts can be corrected or removed, with bounded retries and event history.'], ['Khmer-first output', 'Campaign copy is produced for Khmer-language channels rather than translated at the end.']],
  boundaries: ['It does not publish without approval.', 'It does not guarantee that a platform account will accept a post.', 'It does not share brand context between campaigns.', 'An empty or invalid result stops instead of becoming generic filler.', 'Publishing retries are bounded and recorded.'],
  requirements: { runsOn: 'A local production workspace with configured external services.', needs: ['Brand rules and reference imagery.', 'A campaign owner for approval.', 'Permissioned accounts for each enabled channel.', 'Platform app review wherever the channel requires it.'], optional: ['Telegram remote approval.', 'Configured copy generation and media CDN services.'] },
  dataHandling: 'Image production, brand composition, queues, brand records and event history run locally. Copy generation, CDN delivery and social publishing use the providers and accounts you configure. Campaign rules and reference imagery remain scoped per campaign. Channel availability follows account permission and platform approval.',
  pilotPlan: [['1', 'Scope one brand and campaign', 'Configure rules, references, approval path and confirmed channels.'], ['2', 'Run the pipeline end to end', 'Move a real brief through production and approval into a private channel.'], ['3', 'Enable confirmed public channels', 'Test publishing, retry and correction only where permissions are verified.'], ['4', 'Review the event history', 'Review stalls, rejections and requirements before adding another brand.']],
  faqs: [...khmeradv.faqs, ['How are brands kept separate?', 'Each campaign carries its own rules, references and channel settings.'], ['Can it publish without a human?', 'No. The approval gate is structural.'], ['What happens when publishing fails?', 'Retries are bounded, connection-scoped and recorded.'], ['Can a live post be corrected?', 'On supported channels, corrections and removals are recorded.'], ['Does it produce Khmer copy?', 'Yes. Khmer is a first-class output.'], ['Where does image generation run?', 'Locally.'], ['What if generated copy is empty?', 'The run stops instead of substituting generic content.']],
  roadmap: { label: 'Planned', note: 'Subject to platform approval and account permission. Confirm during assessment.', items: ['TikTok publishing, pending platform review', 'Per-user roles and permissions inside a campaign', 'Scheduled campaign runs'] },
})

Object.assign(hermes, {
  intro: 'Hermes Post turns one idea into a week of posts you actually approve. Write the offer or announcement once. It drafts versions for each channel, prepares the image, and waits for you to say yes. Nothing goes out in your name that you have not read.',
  fit: { forYou: ['Posting consistently keeps slipping because it takes too long.', 'You rewrite the same message for several channels.', 'You want to plan a week in one sitting.', 'You want to approve every post, including from your phone.', 'You are one business with one voice.'], notForYou: ['You manage several client brands.', 'You want posts published without reading them.', 'TikTok is your main channel.', 'You need several levels of approval.'] },
  useCases: [['The Sunday planning hour', 'Bring five useful ideas and leave with an approved, practical content week.'], ['One offer, four channels', 'Create platform-specific versions for Facebook, Instagram, LinkedIn and Telegram from one idea.'], ['Approve from your phone', 'Read, approve or return drafts through Telegram.'], ['Keep your voice', 'Corrections are retained and applied to later drafts.'], ['Publish somewhere else', 'Export as Markdown whenever direct publishing is unavailable or inappropriate.']],
  boundaries: ['It never posts without your approval.', 'It does not publish to TikTok.', 'It is not a multi-brand agency tool.', 'Drafting uses the configured online model providers.', 'Markdown export remains available.'],
  requirements: { runsOn: 'Your configured Hermes Post installation.', needs: ['Ideas, offers or announcements to work from.', 'Permissioned accounts for connected channels.', 'A named owner who approves each post.'], optional: ['ComfyUI or Gemini image workflow.', 'Telegram remote review and approval.'] },
  dataHandling: 'Configured online providers draft the text, so ideas and drafts are sent to those providers. Connected platforms receive approved posts. Your calendar, drafts, approvals and corrections remain in your installation. Markdown export is always available.',
  pilotPlan: [['1', 'Bring one week of material', 'Connect channels and organise offers, stories and announcements.'], ['2', 'Draft, correct, approve', 'Edit until it sounds like you; the corrections are retained.'], ['3', 'Schedule and publish', 'Only the approved week moves into the publishing queue.'], ['4', 'Choose the rhythm', 'Review what needed rewriting and decide whether the workflow is worth continuing.']],
  faqs: [...hermes.faqs, ['Will it sound like me?', 'Not immediately. Your corrections are kept and reused.'], ['Do I approve every post?', 'Yes. That is the design.'], ['What if I dislike an image?', 'Regenerate it, change format or replace it.'], ['Can I use an unsupported channel?', 'Yes. Export the post as Markdown and publish it yourself.'], ['Is my text fully local?', 'No. Drafting uses configured online providers.'], ['How far ahead can I plan?', 'A practical week or month, not a year-long strategy.']],
  roadmap: { label: 'Planned', note: 'Not available today.', items: ['TikTok publishing', 'More image format presets', 'A simple performance view per post'] },
})

Object.assign(kramos, {
  intro: 'KramOS reviews operational documents against verified rules and attaches the source to every finding: the document, the page and the rule applied. Checks are deterministic, evidence is mandatory, and a named reviewer accepts, corrects, resolves or overrides every result.',
  fit: { forYou: ['Evidence is scattered across scans, PDFs, Office files and scripts.', 'Reviewers repeat checks without a consistent decision trail.', 'A finding must point back to its source page.', 'Overrides must remain possible but require a recorded reason.', 'You can run a controlled pilot with a named reviewer.'], notForYou: ['You need hosted production SaaS today.', 'You want software to decide compliance outcomes.', 'You accept findings without supporting evidence.', 'You expect a guaranteed audit result.'] },
  useCases: [['A finding you can defend', 'An expiry finding carries the licence, page and verified rule that produced it.'], ['Mixed-script intake', 'Khmer, English and Chinese detection and OCR run locally across PDF, image and Office formats.'], ['Department-specific checks', 'Tax, audit, customs, logistics, garment, ISO and factory checks remain separate rule families.'], ['Cross-document controls', 'Duplicate and sequence checks run across a document set.'], ['A recorded override', 'A reviewer can override a finding only with a reason that remains in the audit trail.'], ['See where review time goes', 'Analytics expose document type, language, OCR quality and department.']],
  boundaries: ['It does not decide compliance.', 'It does not guarantee an audit result.', 'It does not store a finding without evidence.', 'The findings path is deterministic, not model opinion.', 'It does not replace legal or professional judgement.', 'Reviewer actions and overrides are never silently overwritten.'],
  requirements: { runsOn: 'A controlled local pilot environment.', needs: ['One document family.', 'A verified department rule set.', 'A named human reviewer.', 'Representative real documents for baseline testing.'], optional: ['Additional department rule families after the first pilot is measured.'] },
  findingSteps: ['Secure file, batch or watched-folder intake', 'Local OCR and Khmer, English or Chinese script detection', 'Document classification and department routing', 'Deterministic verified-rule checks', 'Mandatory source, page and rule binding', 'Cross-document duplicate and sequence controls', 'Named human decision with reasoned overrides', 'Linked audit trail and export'],
  dataHandling: 'Document OCR, classification and deterministic checks run locally. Findings, evidence links, reviewer actions and the audit trail are tenant-isolated. KramOS supports compliance review; it does not replace professional judgement or guarantee an audit result.',
  pilotPlan: [['1', 'Choose one document family', 'Configure its verified rules and owning department.'], ['2', 'Run intake and establish a baseline', 'Measure OCR and classification on real documents.'], ['3', 'Review real findings', 'A named reviewer corrects, resolves and records every override.'], ['4', 'Measure before expanding', 'Review quality and reasons for overrides before adding another family.']],
  faqs: [...kramos.faqs, ['Which scripts are handled?', 'Khmer, English and Chinese across PDF, image and Office formats.'], ['Which check families exist?', 'Tax, audit, customs, logistics, garment, ISO and factory.'], ['Do documents leave our environment?', 'The controlled review path runs locally.'], ['How are tenants separated?', 'Records and audit trails are held per tenant.'], ['What happens to low-quality OCR?', 'Quality is surfaced rather than hidden.'], ['Does it detect duplicate invoices?', 'Cross-document duplicate and sequence controls run across the set.'], ['Does it make us compliant?', 'No. Qualified people remain responsible.'], ['Can we export for an auditor?', 'Yes. Findings, evidence and decisions export together.']],
  roadmap: { label: 'In pilot', note: 'Direction, not current availability.', items: ['Hosted multi-tenant deployment', 'Additional department rule sets beyond the current families', 'Complaint and dispute handling', 'Training-record export'] },
})

export const productPages = { luyagent, khmeradv, 'hermes-post': hermes, kramos }

export const productComparison = [
  ['LUYAGENT', 'A seller', 'One shop on Telegram', 'Seller confirms every payment', 'Your own computer', 'luyagent'],
  ['Hermes Post', 'A business owner', 'One business, one voice', 'Owner approves every post', 'Installation and drafting providers', 'hermes-post'],
  ['KhmerADV', 'An agency team', 'Many brands and channels', 'Campaign owner approves before publishing', 'Local production and configured services', 'khmeradv'],
  ['KramOS', 'A compliance reviewer', 'Document families by department', 'Named reviewer decides every finding', 'Local, tenant-isolated processing', 'kramos'],
]
