export const productPages = {
  luyagent: {
    slug: 'luyagent', name: 'LUYAGENT', category: 'Sales automation for Cambodian sellers',
    title: 'Turn customer chats into confirmed orders—without losing control.',
    intro: 'LUYAGENT answers product questions, guides customers through ordering, tracks stock and payment states, and hands sensitive conversations to your staff. Your customer and sales data remain under your control.',
    audience: 'Owner-led shops and Cambodian social sellers handling orders through chat.',
    problemTitle: 'Every missed message can become a missed order.',
    problems: ['Customers repeat the same product and delivery questions.', 'Order details disappear between chat threads and spreadsheets.', 'Payment, stock and fulfilment states are difficult to track.'],
    outcomes: [['Respond consistently', 'Give customers clear answers from approved product and business information.'], ['Track every order', 'Move enquiries through order, stock, payment, confirmation and fulfilment states.'], ['Keep staff in control', 'Hand conversations to a person whenever judgement or approval is required.']],
    workflow: ['Customer question', 'Product and FAQ context', 'Order details', 'Stock check', 'Payment review', 'Seller confirmation', 'Receipt and handoff'],
    capabilities: ['Khmer, English and mixed-language conversations', 'Product catalogue and business knowledge', 'Order and stock status dashboard', 'KHQR and payment-review workflow', 'Human handoff and corrections', 'Customer-controlled deployment options'],
    pilot: '30-day Sales Rescue Pilot',
    pilotCopy: 'Start with one store, one confirmed channel, up to 100 products, a payment workflow and human handoff.',
    faqs: [['Does LUYAGENT confirm payments automatically?', 'Payment confirmation follows rules agreed with the seller. Sensitive or uncertain cases remain human-approved.'], ['Can staff take over a conversation?', 'Yes. Human handoff is part of the operating workflow.'], ['Where is business data stored?', 'Deployment is designed around infrastructure controlled by the customer. Exact boundaries are confirmed during assessment.']],
  },
  khmeradv: {
    slug: 'khmeradv', name: 'KhmerADV', category: 'Local-first media automation',
    title: 'Move from campaign brief to approved content in one controlled workflow.',
    intro: 'KhmerADV connects copy, image production, brand adaptation, review and multi-channel publishing—while keeping human approval before anything goes live.',
    audience: 'Cambodian marketing and operations teams producing frequent multilingual content.',
    problemTitle: 'Your campaign should not disappear between six disconnected tools.',
    problems: ['Briefs, copy, images and feedback live in different places.', 'Brand rules are applied inconsistently across formats and channels.', 'Approvals arrive late and publishing status becomes unclear.'],
    outcomes: [['Produce useful variants', 'Turn one approved brief into channel and format variations.'], ['Stay on brand', 'Apply reusable colours, typography, layouts and production rules.'], ['Approve before publishing', 'Keep review, rejection and human sign-off inside the workflow.']],
    workflow: ['Structured brief', 'Campaign copy', 'Image production', 'Brand adaptation', 'Review and revision', 'Human approval', 'Publishing queue'],
    capabilities: ['Campaign workspace', 'Copy and channel variants', 'ComfyUI image workflows', 'Reusable brand templates', 'Telegram-based review flow', 'Publishing queue and status visibility'],
    pilot: 'Campaign Factory Pilot',
    pilotCopy: 'Bring one campaign. We map the workflow and produce a controlled set of approved assets for confirmed channels.',
    faqs: [['Is KhmerADV a social scheduler?', 'No. It is the production layer connecting the brief, assets, brand adaptation and approval before scheduling.'], ['Can content publish without approval?', 'The workflow keeps human approval before publication.'], ['Can it follow our brand system?', 'Brand inputs and production rules are configured and verified with your team.']],
  },
  khaudit: {
    slug: 'khaudit', name: 'KHAudit', category: 'Compliance and document intelligence',
    title: 'Turn document piles into evidence-linked review workflows.',
    intro: 'KHAudit reads PDF, DOCX and scanned documents in Khmer, English and Chinese; extracts key fields; applies controlled checks; and gives reviewers cited findings and clear next actions.',
    audience: 'Factory compliance, HR, administration and management teams preparing evidence under deadline.',
    problemTitle: 'Audit preparation breaks when evidence is scattered.',
    problems: ['Relevant evidence is buried across mixed files, scans and languages.', 'Teams repeatedly check the same documents under short deadlines.', 'Findings without a clear source trail are difficult to trust or correct.'],
    outcomes: [['Find the right evidence', 'Extract useful fields from multilingual documents and scans.'], ['Review consistent checks', 'Apply controlled rules and connect each finding to supporting evidence.'], ['Prepare a clean package', 'Correct, approve and export an organized review record.']],
    workflow: ['Document intake', 'OCR and layout extraction', 'Structured fields', 'Controlled checks', 'Cited finding and confidence', 'Reviewer approval', 'Export package'],
    capabilities: ['PDF, DOCX and scanned-document intake', 'Khmer, English and Chinese extraction', 'Evidence and page references', 'Controlled rule checks', 'Reviewer correction and approval', 'Private deployment options'],
    pilot: 'Audit Readiness Sprint',
    pilotCopy: 'Start with one controlled document sample and one confirmed review framework. Produce an evidence-gap register and review workflow.',
    disclaimer: 'KHAudit supports document review and audit preparation. It does not replace auditors or legal professionals and does not guarantee compliance or an audit result.',
    faqs: [['Does KHAudit decide whether a company is compliant?', 'No. It supports evidence collection and controlled review. Qualified people remain responsible for conclusions.'], ['Can reviewers correct extracted information?', 'Yes. Human correction and approval are essential parts of the workflow.'], ['Does every finding show its source?', 'The product is designed around traceable evidence, including the source document and relevant location where available.']],
  },
}
