const luyagent = {
  slug: 'luyagent',
  name: 'LUYAGENT',
  category: 'Private sales automation',
  title: 'Turn Telegram conversations into confirmed orders - even when you are away.',
  intro: 'LUYAGENT helps Cambodian shops answer questions, show available products, build carts, collect delivery details and move each customer toward payment. Orders, inventory and customer records remain on the seller\'s own Windows system.',
  audience: 'Solo sellers, family shops and small Cambodian businesses already taking orders through Telegram.',
  problemTitle: 'Every unanswered chat can become a lost order.',
  problems: ['Customers wait for repeated product, stock and delivery answers.', 'Cart, address, payment evidence and order status become disconnected.', 'Sellers need automation without silently approving payments or difficult conversations.'],
  outcomes: [['Fewer missed orders', 'Customers can browse, ask questions and begin checkout without waiting for the seller.'], ['A controlled order flow', 'Product, stock, address, payment method and status stay connected from chat to confirmation.'], ['Seller control when it matters', 'Payments and difficult conversations are surfaced for human review.']],
  workflow: ['Telegram conversation', 'Catalog and FAQ', 'Cart and address', 'COD or bank QR', 'Payment evidence', 'Seller confirmation', 'Receipt and handoff'],
  visuals: {
    problem: 'images/products/luyagent/sales-problems.png',
    outcomes: [
      'images/products/luyagent/fewer-missed-orders.png',
      'images/products/luyagent/controlled-order-flow.png',
      'images/products/luyagent/seller-control.png',
    ],
    workflow: 'images/products/luyagent/order-workflow.png',
  },
  capabilities: ['Khmer and English customer journeys', 'Catalog, search, cart and checkout', 'Stock-aware inventory controls', 'ABA, Wing and ACLEDA payment options', 'Payment screenshot review', 'Order confirmation and PDF receipts', 'Human handoff and assisted replies', 'Spreadsheet product import', 'Local seller dashboard and SQLite records'],
  proof: ['Telegram-ready', 'Seller-approved payments', 'Local operational data'],
  privacy: 'Catalog, orders and customer records are stored in the LUYAGENT installation. Assisted replies currently require configured model access.',
  dataView: 'luyagent',
  pilot: 'LUYAGENT Seller Pilot',
  pilotCopy: 'Bring your current Telegram catalog, payment methods and approval process. We configure one focused seller workflow and verify it with your team.',
  primaryCta: 'Request a LUYAGENT demo',
  secondaryCta: 'See the seller dashboard',
  faqs: [['Does LUYAGENT confirm payments automatically?', 'No. Payment evidence is surfaced for seller verification or rejection.'], ['Which selling channel is ready today?', 'Telegram is the completed sales channel. Additional channels should be confirmed during assessment.'], ['Where is business data stored?', 'The catalog, customer, order and payment records use the local LUYAGENT installation.']],
}

const khmeradv = {
  slug: 'khmeradv',
  name: 'KhmerADV',
  category: 'Agency media operations',
  title: 'Run every brand, campaign and channel from one controlled workspace.',
  intro: 'KhmerADV turns campaign briefs into approved, branded content across social channels. Manage brand rules, visual references, production stages and publishing from one operational command center.',
  audience: 'Agencies and marketing teams operating multiple brands, campaigns and approval flows.',
  problemTitle: 'Agency operations break when every campaign lives in a different tool.',
  problems: ['Brand rules, visual references and channel drafts are easy to mix.', 'Teams cannot see where a production run is blocked or awaiting approval.', 'Publishing status, retries and platform permissions are difficult to track.'],
  outcomes: [['Keep brands separated', 'Manage campaign rules, references and channel settings without mixing client assets.'], ['See the production pipeline', 'Track copy, image, branding, approval and delivery stages in one workspace.'], ['Approve before publishing', 'Review every branded post before it reaches an enabled public channel.']],
  workflow: ['Campaign brief', 'Copy and art direction', 'Image production', 'Brand composition', 'Human approval', 'Channel publishing', 'Delivery and correction'],
  capabilities: ['Multi-campaign workspaces', 'Brand rules and visual references', 'Sequential production queue', 'Copy and ComfyUI image pipeline', 'Remotion brand composition', 'Telegram and dashboard approval', 'Facebook, Instagram, TikTok, LinkedIn and Telegram publishers', 'Retry protection and event history', 'Supported post correction and removal'],
  proof: ['Multi-campaign', 'Human-approved', 'Brand-controlled', 'Channel-ready'],
  privacy: 'KhmerADV combines local media production with configured copy, CDN and social-platform services. Channel availability depends on account permissions and platform approval.',
  dataView: 'khmeradv',
  pilot: 'Agency Command Center Pilot',
  pilotCopy: 'Select one brand and one campaign. We configure its rules, references, approval path and confirmed channels, then run the workflow end to end.',
  primaryCta: 'Plan an agency pilot',
  secondaryCta: 'See the campaign workflow',
  faqs: [['Is KhmerADV only a social scheduler?', 'No. It connects campaign brief, production, branding, approval and publishing.'], ['Can it manage separate brands?', 'Yes. Campaign and brand records keep rules, references and channel settings separated.'], ['Does every channel work automatically?', 'Publishing depends on each platform account, permission and approval status.']],
}

const hermes = {
  slug: 'hermes-post',
  name: 'Hermes Post',
  category: 'Content assistant for small business',
  title: 'Keep your business visible without becoming a full-time content manager.',
  intro: 'Hermes Post helps shops, independent creators and small teams turn a simple idea into an approved post, matching visual and practical publishing schedule.',
  audience: 'Small shops, bloggers, creators and owner-led businesses that need consistent content without agency complexity.',
  problemTitle: 'Posting consistently should not take over your working week.',
  problems: ['Ideas remain unfinished because writing and image creation happen separately.', 'Small teams lose time rewriting the same message for each platform.', 'Drafts, approvals and scheduled posts are difficult to see at a glance.'],
  outcomes: [['Create from one idea', 'Turn an offer, product, announcement or story into platform-ready drafts.'], ['Keep your voice', 'Edit and approve every message before it becomes part of the schedule.'], ['Plan content in one sitting', 'Prepare a practical week or month of posts, then publish or export.']],
  workflow: ['Idea or offer', 'Channel choice', 'Draft and rewrite', 'Image creation', 'Human approval', 'Schedule or publish', 'Export and reuse'],
  capabilities: ['Topic and content-draft creation', 'Platform and content-type variants', 'Editing, rewrite, approval and rejection', 'ComfyUI or Gemini image workflows', 'Selectable image formats', 'Editorial calendar and posting queue', 'Dashboard and Telegram control', 'Markdown export', 'Human-approved correction memory', 'Facebook, Instagram, LinkedIn and Telegram publishing'],
  proof: ['Simple workflow', 'Human approval', 'Content calendar', 'Telegram control'],
  privacy: 'Hermes Post uses configured online providers for text and connected publishing. Manual export remains available when direct publishing is not appropriate.',
  dataView: 'hermes',
  pilot: 'First Content Week',
  pilotCopy: 'Bring one week of offers, announcements or stories. We configure your channels and produce an approved, practical posting queue.',
  primaryCta: 'Create your first content week',
  secondaryCta: 'See how Hermes Post works',
  faqs: [['Is Hermes Post an agency tool?', 'No. It is intentionally simpler than KhmerADV and designed for one small business or creator workflow.'], ['Can I approve from my phone?', 'Telegram can act as a simple remote for review and approval.'], ['Does it publish to TikTok?', 'No TikTok publisher is currently part of Hermes Post. Supported connected channels should be confirmed during setup.']],
}

const kramos = {
  slug: 'kramos',
  name: 'KramOS',
  category: 'Compliance and document control',
  title: 'Every compliance finding should show its evidence.',
  intro: 'KramOS reviews business documents against verified rules, links every issue to its source and keeps the final decision with your team. Built for Cambodian operations and designed to run under your control.',
  audience: 'Cambodian factories, exporters, finance teams, internal auditors and compliance managers.',
  problemTitle: 'A finding without a source is not a defensible decision.',
  problems: ['Operational evidence is scattered across scans, PDFs, Office files and languages.', 'Reviewers repeat the same checks without a consistent decision trail.', 'Generic document tools cannot explain the applicable source or preserve human accountability.'],
  outcomes: [['Review faster', 'Extract important fields and route documents to the relevant operational checks.'], ['Trace every issue', 'Keep the document, source page, applicable rule and reviewer action connected.'], ['Preserve responsibility', 'Correct, resolve, ignore or override with a complete human approval trail.']],
  workflow: ['Secure intake', 'OCR and classification', 'Department routing', 'Deterministic checks', 'Evidence-linked finding', 'Human decision', 'Audit trail and export'],
  capabilities: ['Files, batches and folder intake', 'Khmer, English and Chinese script detection', 'Local PDF, image and Office processing', 'Tax, audit, customs, logistics, garment, ISO and factory checks', 'Mandatory evidence for stored findings', 'Cross-document duplicate and sequence controls', 'Reviewer correction, resolution and override', 'Document, language, OCR and department analytics', 'Tenant isolation and audit trail'],
  proof: ['Evidence-linked', 'Deterministic checks', 'Human-approved', 'Controlled pilot'],
  privacy: 'KramOS is currently positioned as a controlled local pilot. It supports compliance review but does not replace legal or professional judgement and does not guarantee an audit result.',
  dataView: 'kramos',
  pilot: 'KramOS Controlled Pilot',
  pilotCopy: 'Choose one document family - such as supplier invoices, licences or customs declarations. We configure the verified review rules and measure the workflow before expanding.',
  primaryCta: 'Book a controlled pilot',
  secondaryCta: 'See the review workflow',
  disclaimer: 'KramOS supports evidence collection and controlled review. Qualified people remain responsible for compliance conclusions.',
  faqs: [['Is KramOS production SaaS?', 'Not yet. The current offer is a controlled local pilot with a human reviewer.'], ['Can it invent a compliance finding?', 'The findings path uses deterministic controls and requires supporting evidence.'], ['Can reviewers override a result?', 'Yes. Overrides require a recorded reason and remain part of the audit trail.']],
}

export const productPages = {
  luyagent,
  khmeradv,
  'hermes-post': hermes,
  kramos,
  khaudit: kramos,
}
